#!/bin/sh
apk add network-extras
rc-update add udhcpd boot
rc-update add wpa_supplicant boot

ifconfig wlan0 up
echo "===> scanning wifi......."

iwlist wlan0 scan | grep 'ESSID\|Encryption'

echo -n "===> Select ESSID : "
read ESSID
iwconfig wlan0 essid $ESSID

echo "===> wifi password : "
wpa_passphrase $ESSID > /etc/wpa_supplicant/wpa_supplicant.conf

wpa_supplicant -Dwext -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf

cat << EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

auto wlan0
iface wlan0 inet dhcp

auto eth0
iface eth0 inet dhcp
EOF

service networking restart

ifconfig wlan0